/**
 * Planet building statistics.
 *
 * Source: docs/Complete_Units_and_Buildings.md ("Planet Buildings", "Upgrade
 * Paths"), docs/ResourcesEconomy.md.
 *
 * Deviations, all annotated inline:
 *  - The docs specify no HP for any planet building. Values are assigned in
 *    proportion to build cost so Bombers can meaningfully siege structures.
 *  - Planet structures use Fortified armour, per the armour table's
 *    "Planetary Structures" entry.
 */

import type { BuildingDefinition, PlanetBuildingType } from '@fleet-strike/types';

import { cost } from './cost';

/** Documented baseline production interval shared by every factory. */
const BASE_PRODUCTION_INTERVAL = 45;

export const PLANET_BUILDINGS: Readonly<Record<PlanetBuildingType, BuildingDefinition>> = {
  commandCenter: {
    type: 'commandCenter',
    name: 'Capital Command Center',
    nickname: 'Seat of Power',
    site: 'planet',
    cost: cost({}),
    buildTime: 0,
    power: 0,
    maxHp: 5000,
    armor: 'fortified',
    produces: null,
    productionInterval: 0,
    generates: { resource: 'gold', amount: 5 },
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: null,
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    // docs/GameLoop.md: "Command Center ... can't be destroyed, but planet can
    // be captured."
    isDestructible: false,
    upgrades: [],
    texture: 'command_center',
  },

  scoutFactory: {
    type: 'scoutFactory',
    name: 'Scout Factory',
    nickname: 'Light Fighter Hangar',
    site: 'planet',
    cost: cost({ gold: 50 }),
    buildTime: 30,
    power: 1,
    maxHp: 400,
    armor: 'fortified',
    produces: 'scout',
    productionInterval: BASE_PRODUCTION_INTERVAL,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: null,
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      { level: 2, cost: cost({ gold: 100 }), productionInterval: 35, unitHpBonus: 10 },
      {
        level: 3,
        cost: cost({ gold: 200 }),
        productionInterval: 30,
        unitHpBonus: 20,
        unitDamageBonus: 2,
      },
    ],
    texture: 'factory_scout',
  },

  soldierFactory: {
    type: 'soldierFactory',
    name: 'Soldier Factory',
    nickname: 'Standard Fighter Hangar',
    site: 'planet',
    cost: cost({ gold: 100 }),
    buildTime: 40,
    power: 2,
    maxHp: 500,
    armor: 'fortified',
    produces: 'soldier',
    productionInterval: BASE_PRODUCTION_INTERVAL,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: null,
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      { level: 2, cost: cost({ gold: 150 }), productionInterval: 40, unitHpBonus: 20 },
      {
        level: 3,
        cost: cost({ gold: 300 }),
        productionInterval: 35,
        unitHpBonus: 40,
        unitDamageBonus: 5,
      },
    ],
    texture: 'factory_soldier',
  },

  heavyFactory: {
    type: 'heavyFactory',
    name: 'Heavy Factory',
    nickname: 'Capital Ship Foundry',
    site: 'planet',
    cost: cost({ gold: 400 }),
    buildTime: 60,
    power: 5,
    maxHp: 800,
    armor: 'fortified',
    produces: 'heavy',
    productionInterval: BASE_PRODUCTION_INTERVAL,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: null,
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      { level: 2, cost: cost({ gold: 400 }), productionInterval: 40, unitHpBonus: 100 },
      {
        level: 3,
        cost: cost({ gold: 800 }),
        productionInterval: 35,
        unitHpBonus: 200,
        unitDamageBonus: 15,
      },
    ],
    texture: 'factory_heavy',
  },

  medicBay: {
    type: 'medicBay',
    name: 'Medic Bay',
    nickname: 'Support Ship Hangar',
    site: 'planet',
    cost: cost({ gold: 200, crystal: 10 }),
    buildTime: 45,
    power: 3,
    maxHp: 500,
    armor: 'fortified',
    produces: 'medic',
    productionInterval: BASE_PRODUCTION_INTERVAL,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: null,
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      {
        level: 2,
        cost: cost({ gold: 250, crystal: 15 }),
        productionInterval: 40,
        unitHpBonus: 20,
      },
      { level: 3, cost: cost({ gold: 500, crystal: 30 }), productionInterval: 35 },
    ],
    texture: 'factory_medic',
  },

  engineerWorkshop: {
    type: 'engineerWorkshop',
    name: 'Engineer Workshop',
    nickname: 'Constructor Hangar',
    site: 'planet',
    cost: cost({ gold: 150 }),
    buildTime: 40,
    power: 2,
    maxHp: 450,
    armor: 'fortified',
    produces: 'engineer',
    productionInterval: BASE_PRODUCTION_INTERVAL,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: null,
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      { level: 2, cost: cost({ gold: 200 }), productionInterval: 40 },
      { level: 3, cost: cost({ gold: 400 }), productionInterval: 35 },
    ],
    texture: 'factory_engineer',
  },

  bomberFacility: {
    type: 'bomberFacility',
    name: 'Bomber Facility',
    nickname: 'Siege Ship Hangar',
    site: 'planet',
    cost: cost({ gold: 300, gas: 20 }),
    buildTime: 50,
    power: 4,
    maxHp: 650,
    armor: 'fortified',
    produces: 'bomber',
    productionInterval: BASE_PRODUCTION_INTERVAL,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: null,
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      {
        level: 2,
        cost: cost({ gold: 350, gas: 30 }),
        productionInterval: 40,
        unitHpBonus: 30,
        unitDamageBonus: 20,
      },
      { level: 3, cost: cost({ gold: 700, gas: 60 }), productionInterval: 35 },
    ],
    texture: 'factory_bomber',
  },

  sniperDock: {
    type: 'sniperDock',
    name: 'Sniper Dock',
    nickname: 'Precision Fighter Hangar',
    site: 'planet',
    cost: cost({ gold: 250, tungsten: 15 }),
    buildTime: 45,
    power: 3,
    maxHp: 550,
    armor: 'fortified',
    produces: 'sniper',
    productionInterval: BASE_PRODUCTION_INTERVAL,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: null,
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      {
        level: 2,
        cost: cost({ gold: 300, tungsten: 25 }),
        productionInterval: 40,
        unitDamageBonus: 100,
      },
      { level: 3, cost: cost({ gold: 600, tungsten: 50 }), productionInterval: 35 },
    ],
    texture: 'factory_sniper',
  },

  goldMine: {
    type: 'goldMine',
    name: 'Gold Mine',
    nickname: 'Resource Extractor',
    site: 'planet',
    cost: cost({ gold: 80 }),
    buildTime: 30,
    power: 1,
    maxHp: 350,
    armor: 'fortified',
    produces: null,
    productionInterval: 0,
    generates: { resource: 'gold', amount: 3 },
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: null,
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      { level: 2, cost: cost({ gold: 100 }), resourcePerSecond: 5 },
      { level: 3, cost: cost({ gold: 200 }), resourcePerSecond: 8 },
      { level: 4, cost: cost({ gold: 400 }), resourcePerSecond: 12 },
    ],
    texture: 'gold_mine',
  },

  manpowerCenter: {
    type: 'manpowerCenter',
    name: 'Manpower Center',
    nickname: 'Population Hub',
    site: 'planet',
    cost: cost({ gold: 100 }),
    buildTime: 40,
    power: 2,
    maxHp: 400,
    armor: 'fortified',
    produces: null,
    productionInterval: 0,
    generates: { resource: 'manpower', amount: 2 },
    powerCapacity: 0,
    manpowerCapBonus: 50,
    weapon: null,
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      { level: 2, cost: cost({ gold: 150 }), resourcePerSecond: 4, manpowerCapBonus: 100 },
      { level: 3, cost: cost({ gold: 300 }), resourcePerSecond: 7, manpowerCapBonus: 150 },
    ],
    texture: 'manpower_center',
  },

  powerPlant: {
    type: 'powerPlant',
    name: 'Power Plant',
    nickname: 'Energy Generator',
    site: 'planet',
    cost: cost({ gold: 120 }),
    buildTime: 35,
    power: 0,
    maxHp: 400,
    armor: 'fortified',
    produces: null,
    productionInterval: 0,
    generates: null,
    powerCapacity: 10,
    manpowerCapBonus: 0,
    weapon: null,
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    // The docs list "+10 / +15 / +25 power units" per level without saying
    // whether the values are cumulative. Treated as absolute capacity.
    upgrades: [
      { level: 2, cost: cost({ gold: 180 }), powerCapacity: 15 },
      { level: 3, cost: cost({ gold: 350 }), powerCapacity: 25 },
    ],
    texture: 'power_plant',
  },

  researchLab: {
    type: 'researchLab',
    name: 'Research Lab',
    nickname: 'Technology Center',
    site: 'planet',
    cost: cost({ gold: 200 }),
    buildTime: 50,
    power: 3,
    maxHp: 500,
    armor: 'fortified',
    produces: null,
    productionInterval: 0,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: null,
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    // Per-level table from docs/ResourcesEconomy.md, which is more granular
    // than the single line in docs/GameLoop.md.
    upgrades: [
      { level: 2, cost: cost({ gold: 300 }), upgradeDiscount: 0.25, productionSpeedBonus: 0.05 },
      { level: 3, cost: cost({ gold: 600 }), upgradeDiscount: 0.4, productionSpeedBonus: 0.1 },
    ],
    texture: 'research_lab',
  },
};

/** Level 1 upgrade discount granted by owning any Research Lab. */
export const RESEARCH_LAB_BASE_DISCOUNT = 0.15;
