/**
 * Moon building statistics — the defensive tier.
 *
 * Source: docs/Complete_Units_and_Buildings.md ("Moon Buildings").
 *
 * Deviations, annotated inline:
 *  - The docs specify no power draw for moon buildings, so all are zero.
 *  - The Missile Silo's rate of fire is self-contradictory ("0.25 shots/sec
 *    (15 second reload)"); the explicit reload wins.
 *  - Upgrade entries stated as "+800 radius" / "+700 range" on smaller bases
 *    are read as absolute values, matching the surrounding table style.
 */

import type { BuildingDefinition, MoonBuildingType } from '@fleet-strike/types';

import { cost } from './cost';

export const MOON_BUILDINGS: Readonly<Record<MoonBuildingType, BuildingDefinition>> = {
  plasmaTurret: {
    type: 'plasmaTurret',
    name: 'Plasma Turret',
    nickname: 'Anti-Ship Battery',
    site: 'moon',
    cost: cost({ gold: 150, gas: 10 }),
    buildTime: 40,
    power: 0,
    maxHp: 800,
    armor: 'fortified',
    produces: null,
    productionInterval: 0,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: {
      name: 'Heavy Plasma Cannons',
      weaponType: 'plasma',
      damage: 80,
      rateOfFire: 1,
      range: 700,
      projectileSpeed: 450,
      areaOfEffect: 0,
      chargeTime: 0,
    },
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      {
        level: 2,
        cost: cost({ gold: 200, gas: 15 }),
        hpBonus: 200,
        damageBonus: 20,
        rangeBonus: 100,
      },
      { level: 3, cost: cost({ gold: 400, gas: 30 }), hpBonus: 400 },
    ],
    texture: 'turret_plasma',
  },

  flakBattery: {
    type: 'flakBattery',
    name: 'Flak Battery',
    nickname: 'Anti-Swarm Defense',
    site: 'moon',
    cost: cost({ gold: 120 }),
    buildTime: 35,
    power: 0,
    maxHp: 600,
    armor: 'fortified',
    produces: null,
    productionInterval: 0,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: {
      name: 'Rapid-Fire Flak Cannons',
      weaponType: 'flak',
      damage: 25,
      rateOfFire: 3,
      range: 600,
      projectileSpeed: 400,
      areaOfEffect: 90,
      chargeTime: 0,
    },
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      { level: 2, cost: cost({ gold: 150 }), hpBonus: 150 },
      { level: 3, cost: cost({ gold: 300 }), hpBonus: 300 },
    ],
    texture: 'turret_flak',
  },

  laserArray: {
    type: 'laserArray',
    name: 'Laser Array',
    nickname: 'Long-Range Defense',
    site: 'moon',
    cost: cost({ gold: 200, crystal: 15 }),
    buildTime: 45,
    power: 0,
    maxHp: 500,
    armor: 'fortified',
    produces: null,
    productionInterval: 0,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: {
      name: 'Focused Laser Array',
      weaponType: 'laser',
      damage: 120,
      rateOfFire: 0.75,
      range: 1000,
      projectileSpeed: 0,
      areaOfEffect: 0,
      chargeTime: 0,
    },
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      { level: 2, cost: cost({ gold: 250, crystal: 25 }), hpBonus: 100, damageBonus: 50 },
      { level: 3, cost: cost({ gold: 500, crystal: 50 }), hpBonus: 200 },
    ],
    texture: 'turret_laser',
  },

  shieldGenerator: {
    type: 'shieldGenerator',
    name: 'Shield Generator',
    nickname: 'Defensive Barrier',
    site: 'moon',
    cost: cost({ gold: 250, crystal: 30 }),
    buildTime: 50,
    power: 0,
    maxHp: 400,
    armor: 'fortified',
    produces: null,
    productionInterval: 0,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: null,
    auraRadius: 600,
    repairPerSecond: 0,
    shieldHp: 2000,
    shieldRegen: 50,
    shieldRegenDelay: 5,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      { level: 2, cost: cost({ gold: 350, crystal: 50 }), hpBonus: 1000, rangeBonus: 800 },
      { level: 3, cost: cost({ gold: 700, crystal: 100 }), hpBonus: 2000 },
    ],
    texture: 'shield_generator',
  },

  radarStation: {
    type: 'radarStation',
    name: 'Radar Station',
    nickname: 'Surveillance Network',
    site: 'moon',
    cost: cost({ gold: 100 }),
    buildTime: 30,
    power: 0,
    maxHp: 300,
    armor: 'light',
    produces: null,
    productionInterval: 0,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: null,
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 1200,
    isDestructible: true,
    upgrades: [
      { level: 2, cost: cost({ gold: 150 }), hpBonus: 500, rangeBonus: 600 },
      { level: 3, cost: cost({ gold: 300 }), hpBonus: 700, rangeBonus: 1000 },
    ],
    texture: 'radar_station',
  },

  missileSilo: {
    type: 'missileSilo',
    name: 'Missile Silo',
    nickname: 'Strategic Bombardment',
    site: 'moon',
    cost: cost({ gold: 350, gas: 40 }),
    buildTime: 60,
    power: 0,
    maxHp: 1000,
    armor: 'fortified',
    produces: null,
    productionInterval: 0,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: {
      name: 'Long-Range Missiles',
      weaponType: 'rocket',
      damage: 200,
      // The "15 second reload" is used rather than the contradictory
      // "0.25 shots/sec" on the same line.
      rateOfFire: 1 / 15,
      range: 1500,
      projectileSpeed: 150,
      areaOfEffect: 200,
      chargeTime: 0,
    },
    auraRadius: 0,
    repairPerSecond: 0,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      { level: 2, cost: cost({ gold: 500, gas: 60 }), hpBonus: 300, damageBonus: 100 },
      { level: 3, cost: cost({ gold: 1000, gas: 120 }), hpBonus: 500 },
    ],
    texture: 'missile_silo',
  },

  repairStation: {
    type: 'repairStation',
    name: 'Repair Station',
    nickname: 'Maintenance Facility',
    site: 'moon',
    cost: cost({ gold: 180, crystal: 15 }),
    buildTime: 40,
    power: 0,
    maxHp: 450,
    armor: 'medium',
    produces: null,
    productionInterval: 0,
    generates: null,
    powerCapacity: 0,
    manpowerCapBonus: 0,
    weapon: null,
    auraRadius: 500,
    repairPerSecond: 20,
    shieldHp: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    visionRadius: 0,
    isDestructible: true,
    upgrades: [
      { level: 2, cost: cost({ gold: 250, crystal: 25 }), hpBonus: 150, rangeBonus: 700 },
      { level: 3, cost: cost({ gold: 500, crystal: 50 }), hpBonus: 300 },
    ],
    texture: 'repair_station',
  },
};
