import { Application, Container, Graphics, Text, TextStyle } from 'pixi.js';
import './style.css';import { BASE_HP, SHIPS, WAVE_SECONDS } from '../shared/config';import type { GameEvent, MatchState, Row, ServerMessage, Ship, ShipType } from '../shared/types';
import './builder.css';
import './neon.css';
const root=document.querySelector<HTMLDivElement>('#app')!;
root.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><div class="brand-mark">✦</div><span>FLEET STRIKE</span></div><div class="center-stat"><div class="wave" id="wave">AWAITING RIVAL</div><div class="timer" id="timer">00:30</div></div><div class="base enemy"><div><div id="enemyName">ENEMY BASE</div><div class="hpbar"><div class="hpfill" id="enemyHp"></div></div></div><span class="hpnum" id="enemyHpNum">500</span></div></header><main class="arena" id="arena"><div class="arena-overlay"><div class="room-chip" id="roomChip">ROOM —</div><div class="horn" id="horn">⚠ WAVE DEPLOYED</div></div></main><section class="bottom"><div class="wallet"><span class="wallet-label">War chest</span><span class="gold" id="gold">80 G</span><span class="income">▲ +10 per second</span><div style="margin-top:14px" class="base"><div><div id="myName">YOUR BASE</div><div class="hpbar"><div class="hpfill" id="myHp"></div></div></div><span class="hpnum" id="myHpNum">500</span></div></div><div class="cards" id="cards"></div><div class="rows"><span class="section-label">Deployment row</span>${['Vanguard','Mid line','Rear guard'].map((x,i)=>`<button class="rowbtn ${i===0?'active':''}" data-row="${i}"><span class="rowname">${x}</span><span class="tokens" id="tokens${i}">—</span></button>`).join('')}</div></section></div><div class="modal" id="lobby"><div class="panel"><h1>Fleet <span>Strike</span></h1><p class="tagline">Build your fleet. Read the enemy. Break their line.</p><input id="name" maxlength="18" placeholder="CAPTAIN NAME" value="Admiral"><div class="actions"><button class="primary" id="create">Create room</button><button class="secondary" id="training">Solo training</button></div><div class="joinline"><input id="codeInput" maxlength="4" placeholder="ROOM CODE"><button class="secondary" id="join">Join</button></div><div class="error" id="error"></div></div></div><div class="modal hidden" id="waiting"><div class="panel waiting"><span class="section-label">Broadcast this room code</span><div class="code" id="waitCode"></div><p>Waiting for a rival captain…</p><p class="small">Open another browser window and join with this code.</p></div></div><div class="modal hidden" id="gameover"><div class="panel gameover"><span class="section-label">Battle concluded</span><h1 id="result">Victory</h1><p id="resultText" class="tagline"></p><button class="primary" id="rematch">Rematch</button></div></div><div class="toast" id="toast"></div>`;
let socket:WebSocket|null=null,player:0|1=0,state:MatchState|null=null,row:Row=0,lastEvents=new Set<string>(),selected:ShipType='interceptor',placementArmed=true;
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;const arena=$<HTMLElement>('#arena');
const app=new Application();await app.init({resizeTo:arena,background:0x082b3a,antialias:true,preference:'webgpu'});arena.prepend(app.canvas);
const sea=new Graphics(),world=new Container(),fx=new Container();app.stage.addChild(sea,world,fx);
function drawSea(){const w=app.screen.width,h=app.screen.height,t=performance.now()/1000,pulse=.22+Math.sin(t*1.4)*.04;sea.clear().rect(0,0,w,h).fill(0x010108);for(let i=0;i<=18;i++){const y=i/18*h,bend=Math.sin(i*.8+t*.25)*8;sea.moveTo(0,y).bezierCurveTo(w*.32,y+bend,w*.68,y-bend,w,y).stroke({color:i%3===0?0x5c28b8:0x202060,width:i%3===0?1.3:1,alpha:pulse})}for(let i=-10;i<=10;i++){const bottom=w/2+i*w*.085;sea.moveTo(w/2+i*5,h*.48).lineTo(bottom,h).stroke({color:i%2?0x163d8d:0x712fba,width:1,alpha:.22})}for(let i=0;i<70;i++){const x=(i*149)%Math.max(1,w),y=(i*83)%Math.max(1,h),a=.12+Math.sin(t*2+i)*.08;sea.circle(x,y,i%9===0?1.5:.7).fill({color:i%3===0?0xff5cf4:i%3===1?0x6cecff:0x8cff62,alpha:a})}sea.rect(w/2-1,0,2,h).fill({color:0xc564ff,alpha:.2})}
function shipGraphic(s:Ship,w:number,h:number){const c=SHIPS[s.type],x=w*(s.x/100),y=h*(s.y/100),g=new Graphics(),dir=s.owner===0?1:-1,pulse=1+Math.sin(performance.now()/120+s.x)*.12;g.blendMode='add';g.moveTo(x-dir*13,y).lineTo(x-dir*38,y-3).stroke({color:c.color,width:8,alpha:.055}).moveTo(x-dir*12,y).lineTo(x-dir*31,y).stroke({color:c.color,width:2,alpha:.55});g.circle(x,y,24*pulse).fill({color:c.color,alpha:.055}).circle(x,y,17).fill({color:c.color,alpha:.07});g.moveTo(x+dir*16,y).lineTo(x-dir*9,y-8).lineTo(x-dir*17,y).lineTo(x-dir*9,y+8).closePath().fill({color:c.color,alpha:.22}).stroke({color:c.color,width:2.2,alpha:1});g.moveTo(x+dir*10,y).lineTo(x-dir*8,y-4).lineTo(x-dir*12,y).lineTo(x-dir*8,y+4).closePath().stroke({color:0xffffff,width:1,alpha:.95});g.rect(x-17,y-17,34,3).fill({color:0x120926,alpha:.9}).rect(x-17,y-17,34*(s.hp/s.maxHp),3).fill({color:s.owner===player?0x71f7ff:0xff5c91,alpha:1});if(s.type==='dreadnought')g.rect(x-5,y-5,10,10).stroke({color:0xfff7c0,width:1.5,alpha:.9});return g}
function queuedShipGraphic(type:ShipType,owner:0|1,row:Row,index:number,w:number,h:number){
  const cfg=SHIPS[type],dir=owner===0?1:-1;
  // Queued fleets form up just inside their base, spreading inward along the lane.
  const x=owner===0?58+index*31:w-58-index*31,y=h*(.19+row*.31);
  const g=new Graphics();
  g.circle(x,y,18).fill({color:cfg.color,alpha:.09}).stroke({color:cfg.color,width:1,alpha:.38});
  g.moveTo(x+dir*13,y).lineTo(x-dir*8,y-7).lineTo(x-dir*14,y).lineTo(x-dir*8,y+7).closePath().fill(cfg.color).stroke({color:0xf0fdff,width:1,alpha:.7});
  if(type==='dreadnought')g.rect(x-4,y-4,8,8).fill(0x17333d);
  return g;
}
function placedShipGraphic(type:ShipType,owner:0|1,xNorm:number,yNorm:number,w:number,h:number){
  const cfg=SHIPS[type],x=xNorm*w,y=24+yNorm*(h-48),dir=owner===0?1:-1,g=new Graphics();
  g.blendMode='add';g.circle(x,y,25).fill({color:cfg.color,alpha:.055}).circle(x,y,20).fill({color:cfg.color,alpha:.08}).stroke({color:cfg.color,width:1.5,alpha:.8});
  g.moveTo(x+dir*15,y).lineTo(x-dir*9,y-8).lineTo(x-dir*16,y).lineTo(x-dir*9,y+8).closePath().fill({color:cfg.color,alpha:.2}).stroke({color:cfg.color,width:2,alpha:1});
  if(type==='dreadnought')g.rect(x-5,y-4,10,8).fill(0x17333d);
  return g;
}
function render(){
  drawSea();world.removeChildren();if(!state)return;const w=app.screen.width,h=app.screen.height;
  for(const side of [0,1] as const){
    const x=side===0?30:w-30,y=h/2,isMine=side===player,baseColor=isMine?0x6cecff:0xff4f9a,t=performance.now()/900;
    const nexus=new Graphics();nexus.blendMode='add';nexus.circle(x,y,44+Math.sin(t)*3).fill({color:baseColor,alpha:.035}).circle(x,y,31).fill({color:baseColor,alpha:.07}).stroke({color:baseColor,width:2,alpha:.8}).circle(x,y,13).fill({color:0xffffff,alpha:.7}).stroke({color:baseColor,width:4,alpha:1});
    for(let ring=0;ring<2;ring++){const radius=22+ring*14,turn=t*(ring?-.7:1);for(let i=0;i<4;i++){const a=turn+i*Math.PI/2,b=turn+(i+1)*Math.PI/2;nexus.moveTo(x+Math.cos(a)*radius,y+Math.sin(a)*radius).lineTo(x+Math.cos(b)*radius,y+Math.sin(b)*radius).stroke({color:ring?0x9d5cff:baseColor,width:ring?1:2,alpha:.8})}}
    world.addChild(nexus);
    const label=new Text({text:isMine?'YOUR NEXUS':'ENEMY NEXUS',style:new TextStyle({fontFamily:'Inter',fontSize:9,fontWeight:'600',fill:isMine?0x72d9ee:0xff8a76,letterSpacing:1})});label.anchor.set(.5,.5);label.x=x;label.y=y+57;world.addChild(label);
    const zoneX=side===0?w*.04:w*.62,zoneW=w*.34;
    world.addChild(new Graphics().rect(zoneX,24,zoneW,h-48).fill({color:isMine?0x55d9ff:0xff795f,alpha:isMine&&placementArmed?.055:.025}).stroke({color:isMine?0x55d9ff:0xff795f,width:1,alpha:isMine?.25:.12}));
    for(const p of state.players[side].placements)world.addChild(placedShipGraphic(p.type,side,p.x,p.y,w,h));
  }
  for(const s of state.ships)world.addChild(shipGraphic(s,w,h));
}app.ticker.add(render);
function card(type:ShipType){const c=SHIPS[type];return `<button class="card ${type===selected?'selected':''}" data-ship="${type}" style="--color:#${c.color.toString(16).padStart(6,'0')}"><div class="ship-icon">◢</div><div class="card-name">${c.name}</div><div class="card-role">${c.blurb}</div><div class="stats"><span>♥ ${c.hp}</span><span>⚔ ${c.damage}</span></div><span class="cost">${c.cost} G</span></button>`}
function buildCards(){const el=$('#cards');el.innerHTML=(Object.keys(SHIPS) as ShipType[]).map(card).join('');el.querySelectorAll<HTMLButtonElement>('.card').forEach(b=>b.onclick=()=>{selected=b.dataset.ship as ShipType;placementArmed=true;buildCards();toast(`${SHIPS[selected].name} selected — click your deployment zone`)})}buildCards();
function buy(ship:ShipType,x:number,y:number){if(!state||state.phase!=='battle')return;socket?.send(JSON.stringify({type:'buy',ship,x,y}));}
app.canvas.addEventListener('pointerdown',e=>{if(!state||state.phase!=='battle'||!placementArmed)return;const rect=app.canvas.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width,y=Math.max(0,Math.min(1,(e.clientY-rect.top-24)/(rect.height-48))),valid=player===0?x>=.04&&x<=.38:x>=.62&&x<=.96;if(!valid){toast('Place ships inside your highlighted deployment zone');return}if(state.players[player].gold<SHIPS[selected].cost){toast('Not enough gold');return}buy(selected,x,y)});
document.querySelectorAll<HTMLButtonElement>('.rowbtn').forEach(b=>b.onclick=()=>{row=Number(b.dataset.row) as Row;document.querySelectorAll('.rowbtn').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
function connect(kind:'create'|'join',code=''){socket?.close();socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);socket.onopen=()=>socket!.send(JSON.stringify({type:kind,name:$<HTMLInputElement>('#name').value||'Admiral',room:code}));socket.onmessage=e=>handle(JSON.parse(e.data));socket.onerror=()=>toast('Cannot reach battle server');}
function handle(m:ServerMessage){if(m.type==='error')toast(m.message);if(m.type==='welcome'){player=m.player;$('#roomChip').textContent=`ROOM ${m.room}`;$('#waitCode').textContent=m.room;$('#lobby').classList.add('hidden');if(player===0)$('#waiting').classList.remove('hidden')}if(m.type==='state'){state=m.state;if(state.phase==='battle')$('#waiting').classList.add('hidden');updateUI();processEvents();}}
function updateUI(){if(!state)return;const me=state.players[player],enemy=state.players[player===0?1:0];$('#gold').textContent=`${Math.floor(me.gold)} G`;$('#myName').textContent=me.name;$('#enemyName').textContent=enemy.name;$('#myHpNum').textContent=String(me.baseHp);$('#enemyHpNum').textContent=String(enemy.baseHp);($('#myHp') as HTMLElement).style.width=`${me.baseHp/BASE_HP*100}%`;($('#enemyHp') as HTMLElement).style.width=`${enemy.baseHp/BASE_HP*100}%`;$('#wave').textContent=state.phase==='battle'?`WAVE ${state.wave+1} INBOUND`:'AWAITING RIVAL';$('#timer').textContent=`00:${Math.max(0,Math.ceil(state.nextWave)).toString().padStart(2,'0')}`;for(const r of [0,1,2] as Row[]){const q=me.placements.filter(p=>Math.round(p.y*2)===r);$(`#tokens${r}`).innerHTML=q.length?q.map(p=>`<span class="queued-unit" style="--unit:#${SHIPS[p.type].color.toString(16).padStart(6,'0')}">${SHIPS[p.type].name}</span>`).join(''):'<span class="queue-empty">EMPTY SECTOR</span>'}document.querySelectorAll<HTMLButtonElement>('.card').forEach(b=>b.disabled=me.gold<SHIPS[b.dataset.ship as ShipType].cost);if(state.phase==='ended'){const win=state.winner===player;$('#result').textContent=win?'VICTORY':'DEFEAT';$('#resultText').textContent=win?'Enemy command has fallen. The sea is yours.':'Your base was destroyed. Rebuild the fleet.';$('#gameover').classList.remove('hidden')}}
function processEvents(){if(!state)return;for(const e of state.events){if(lastEvents.has(e.id))continue;lastEvents.add(e.id);if(e.type==='launch'){const h=$('#horn');h.classList.add('show');setTimeout(()=>h.classList.remove('show'),1700)}if(e.x!=null&&(e.y!=null||e.row!=null))burst(e)}if(lastEvents.size>100)lastEvents=new Set(state.events.map(e=>e.id))}
function burst(e:GameEvent){
  const x=app.screen.width*(e.x!/100),y=app.screen.height*((e.y??50)/100),isDeath=e.type==='death'||e.type==='baseHit',palette=isDeath?[0xff4fa3,0x9d5cff,0x65f7ff,0xffd85a]:[0x65f7ff,0xffffff,0x9dff68],count=isDeath?28:8,group=new Container();group.blendMode='add';fx.addChild(group);
  const ring=new Graphics().circle(0,0,isDeath?8:3).stroke({color:palette[0],width:isDeath?3:1.5,alpha:1}).circle(0,0,isDeath?15:6).stroke({color:0xffffff,width:1,alpha:.75});ring.x=x;ring.y=y;group.addChild(ring);
  const particles=Array.from({length:count},(_,i)=>{const angle=(i/count)*Math.PI*2+Math.random()*.35,speed=(isDeath?2.2:.8)+Math.random()*(isDeath?4:1.5),p=new Graphics().rect(-1,-4,isDeath?2:1,isDeath?8:4).fill({color:palette[i%palette.length],alpha:1});p.x=x;p.y=y;p.rotation=angle+Math.PI/2;group.addChild(p);return{p,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed}});
  const flash=new Graphics().circle(x,y,isDeath?20:7).fill({color:0xffffff,alpha:.8}).circle(x,y,isDeath?42:14).fill({color:palette[0],alpha:.14});group.addChild(flash);let life=1;
  const animate=()=>{life-=isDeath?.035:.075;ring.scale.set(1+(1-life)*(isDeath?5:2));ring.alpha=life;flash.alpha=Math.max(0,life*1.4-.5);for(const q of particles){q.p.x+=q.vx;q.p.y+=q.vy;q.vx*=.985;q.vy*=.985;q.p.alpha=life;q.p.scale.y=.5+life}if(life<=0){app.ticker.remove(animate);group.destroy({children:true})}};app.ticker.add(animate);
}
function toast(msg:string){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
$('#create').onclick=()=>connect('create');$('#join').onclick=()=>connect('join',($('#codeInput') as HTMLInputElement).value.trim().toUpperCase());$('#training').onclick=()=>{toast('Create a room, then join it from a second window for local training.')};$('#rematch').onclick=()=>{socket?.send(JSON.stringify({type:'rematch'}));$('#gameover').classList.add('hidden')};window.addEventListener('resize',drawSea);
